/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */

package avp.fitnessexercisecomponent;

/**
 *
 * @author Albert
 */

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Albert
 */
public class FitnessExerciseComponent extends javax.swing.JPanel {

    private String exerciseName;
    private String exerciseUserName;
    private String attemptDateTime;
    private String attemptState;

    public String getExerciseName() {
        return exerciseName;
    }

    public void setExerciseName(String exerciseName) {
        this.exerciseName = exerciseName;
        lblExerciseName.setText(exerciseName);
    }

    public String getExerciseUserName() {
        return exerciseUserName;
    }

    public void setExerciseUserName(String exerciseUserName) {
        this.exerciseUserName = exerciseUserName;
        lblUserName.setText(exerciseUserName);
    }

    public String getAttemptDateTime() {
        return attemptDateTime;
    }

    public void setAttemptDateTime(String attemptDateTime) {
        this.attemptDateTime = attemptDateTime;
        lblDateTime.setText(attemptDateTime);
    }

    public String getAttemptState() {
        return attemptState;
    }

    public void setAttemptState(String attemptState) {
        this.attemptState = attemptState;
        //Change image based on state
    }

    public FitnessExerciseComponent() {
        initComponents();
        lblIcon.setText("");
        addMouseListener(new MouseAdapter() {
            private int initialX;

            @Override
            public void mousePressed(MouseEvent e) {
                initialX = e.getX();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                int finalX = e.getX();
                int diffX = finalX - initialX;

                //FitnessExerciseComponent parent = (FitnessExerciseComponent) ((Component)e.getSource()).getParent();
                if (diffX > 0) {
                    onSwipeRight();
                } else if (diffX < 0) {
                    onSwipeLeft();
                }
            }

            public void onSwipeRight() {
                // Handle right swipe
                System.out.println("Swiped right");
                //System.out.println(parent.getExerciseName());
                lblIcon.setIcon(new ImageIcon(getClass().getResource("/check-mark.png")));
            }

            public void onSwipeLeft() {
                // Handle left swipe
                System.out.println("Swiped left");
                //System.out.println(parent.getExerciseName());
                lblIcon.setIcon(new ImageIcon(getClass().getResource("/close.png")));
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblExerciseName = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        lblExerciseName.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblExerciseName.setText("Exercise");
        add(lblExerciseName, new java.awt.GridBagConstraints());

        lblIcon.setText("Icon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 111, 0, 33);
        add(lblIcon, gridBagConstraints);

        lblUserName.setText("User");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 6, 6, 0);
        add(lblUserName, gridBagConstraints);

        lblDateTime.setText("DateTime");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 54, 6, 0);
        add(lblDateTime, gridBagConstraints);
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblExerciseName;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration                   

}
